---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 100m
        ports:
        - containerPort: 80
          protocol: TCP
          name: nginx

