---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argonginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argonginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: argonginx
    spec:
      containers:
      - image: nginx:latest
        name: argonginx
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 384Mi
            cpu: 500m
        ports:
        - containerPort: 80
          protocol: TCP
          name: argonginx

