apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx-test
  type: LoadBalancer
  ports:
    - name: nginx-test
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 10.0.1.210
